# -*- coding: utf-8 -*-
"""week 2(exp-2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ose_mP-yDyWJg5no3W11z0YiQ5xEKkwQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages

df = pd.read_csv("/content/placement_predict_50k.csv")

sns.set_style("whitegrid")

fig1 = plt.figure(figsize=(10, 6))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis", yticklabels=False)
plt.title("Missingness Heatmap - Placement Prediction Dataset")
plt.xlabel("Columns")
plt.tight_layout()
plt.show()

num_cols = df.select_dtypes(include=np.number).columns

fig2, axes = plt.subplots(2, 3, figsize=(15, 8))

for i, col in enumerate(num_cols[:6]):
    row, colpos = divmod(i, 3)
    sns.histplot(df[col].dropna(), bins=30, kde=True,
                 ax=axes[row, colpos], color="steelblue")
    axes[row, colpos].set_title(f"Distribution of {col}")

plt.tight_layout()
plt.show()

fig3 = sns.pairplot(df[num_cols[:4]])
fig3.fig.suptitle("Pairplot of Numerical Features", y=1.02)
plt.show()

fig4 = plt.figure(figsize=(10, 8))

numeric_df = df.select_dtypes(include=['int64', 'float64'])
corr_matrix = numeric_df.corr()

sns.heatmap(corr_matrix,
            annot=True,
            fmt=".2f",
            cmap="coolwarm",
            square=True,
            linewidths=0.5)

plt.title("Correlation Heatmap - Numerical Features")
plt.tight_layout()
plt.show()

fig5, axes5 = plt.subplots(2, 3, figsize=(15, 8))

for i, col in enumerate(num_cols[:6]):
    row, colpos = divmod(i, 3)
    sns.boxplot(y=df[col],
                ax=axes5[row, colpos],
                color="lightcoral")
    axes5[row, colpos].set_title(f"Boxplot of {col}")

plt.tight_layout()
plt.show()

pdf = PdfPages("EDA_Report.pdf")

pdf.savefig(fig1)
pdf.savefig(fig2)
pdf.savefig(fig3.fig)
pdf.savefig(fig4)
pdf.savefig(fig5)

pdf.close()

print("EDA_Report.pdf has been created successfully.")

from google.colab import files
files.download("EDA_Report.pdf")