# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrGai7X5Lq8lsy8AkVMz3W2bTRjbsIz3
"""

# ============================================================
# TRAVEL TIME PREDICTION USING RIDGE AND LASSO REGRESSION
# DATA ANALYTICS + EDA
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# 1. UPLOAD DATASET
# ============================================================

from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))
df = pd.read_csv(filename)

# ============================================================
# DATA ANALYTICS
# ============================================================

# 2. DATASET

print("DATASET")
print(df.head())


# 3. SHAPE

print("\nSHAPE")
print(df.shape)


# 4. COLUMN NAMES

print("\nCOLUMN NAMES")
print(df.columns.tolist())


# 5. DATA TYPES

print("\nDATA TYPES")
print(df.dtypes)


# 6. NULL VALUES

print("\nNULL VALUES")
print(df.isnull().sum())


# 7. TOTAL NULL VALUES

print("\nTOTAL NULL VALUES")
print(df.isnull().sum().sum())


# 8. DUPLICATE ROWS

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())


# 9. STATISTICAL SUMMARY

print("\nSTATISTICAL SUMMARY")
print(df.describe())


# 10. AVERAGE TRAVEL TIME

print("\nAVERAGE TRAVEL TIME")
print(df["Travel_Time_Minutes"].mean())


# 11. AVERAGE DISTANCE

print("\nAVERAGE DISTANCE")
print(df["Distance_km"].mean())


# 12. AVERAGE SPEED

print("\nAVERAGE SPEED")
print(df["Avg_Speed_kmph"].mean())


# 13. AVERAGE NUMBER OF SIGNALS

print("\nAVERAGE NUMBER OF SIGNALS")
print(df["Number_of_Signals"].mean())


# 14. TRAVEL TIME RANGE

print("\nTRAVEL TIME RANGE")
print("Minimum:",
      df["Travel_Time_Minutes"].min())

print("Maximum:",
      df["Travel_Time_Minutes"].max())


# 15. CATEGORICAL DATA ANALYSIS

categorical_columns = [
    "Traffic_Level",
    "Weather",
    "Road_Type",
    "Vehicle_Type",
    "Day_of_Week",
    "Time_of_Day"
]

for column in categorical_columns:

    print("\n", column)
    print(df[column].value_counts())


# 16. TRAVEL TIME BY TRAFFIC LEVEL

print("\nTRAVEL TIME BY TRAFFIC LEVEL")

print(
    df.groupby("Traffic_Level")[
        "Travel_Time_Minutes"
    ].mean()
)


# 17. TRAVEL TIME BY WEATHER

print("\nTRAVEL TIME BY WEATHER")

print(
    df.groupby("Weather")[
        "Travel_Time_Minutes"
    ].mean()
)


# 18. TRAVEL TIME BY ROAD TYPE

print("\nTRAVEL TIME BY ROAD TYPE")

print(
    df.groupby("Road_Type")[
        "Travel_Time_Minutes"
    ].mean()
)


# 19. TRAVEL TIME BY VEHICLE TYPE

print("\nTRAVEL TIME BY VEHICLE TYPE")

print(
    df.groupby("Vehicle_Type")[
        "Travel_Time_Minutes"
    ].mean()
)


# 20. TRAVEL TIME BY TIME OF DAY

print("\nTRAVEL TIME BY TIME OF DAY")

print(
    df.groupby("Time_of_Day")[
        "Travel_Time_Minutes"
    ].mean()
)


# 21. CORRELATION

numerical_columns = [
    "Distance_km",
    "Avg_Speed_kmph",
    "Number_of_Signals",
    "Travel_Time_Minutes"
]

correlation = df[numerical_columns].corr()

print("\nCORRELATION")
print(correlation)


# ============================================================
# DATA ANALYTICS GRAPHS
# ============================================================


# 22. TRAFFIC LEVEL VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.barplot(
    data=df,
    x="Traffic_Level",
    y="Travel_Time_Minutes"
)

plt.title("Average Travel Time by Traffic Level")
plt.xlabel("Traffic Level")
plt.ylabel("Average Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# 23. WEATHER VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.barplot(
    data=df,
    x="Weather",
    y="Travel_Time_Minutes"
)

plt.title("Average Travel Time by Weather")
plt.xlabel("Weather")
plt.ylabel("Average Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# 24. ROAD TYPE VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.barplot(
    data=df,
    x="Road_Type",
    y="Travel_Time_Minutes"
)

plt.title("Average Travel Time by Road Type")
plt.xlabel("Road Type")
plt.ylabel("Average Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# 25. VEHICLE TYPE VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.barplot(
    data=df,
    x="Vehicle_Type",
    y="Travel_Time_Minutes"
)

plt.title("Average Travel Time by Vehicle Type")
plt.xlabel("Vehicle Type")
plt.ylabel("Average Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# 26. TIME OF DAY VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.barplot(
    data=df,
    x="Time_of_Day",
    y="Travel_Time_Minutes"
)

plt.title("Average Travel Time by Time of Day")
plt.xlabel("Time of Day")
plt.ylabel("Average Travel Time (Minutes)")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()


# 27. DISTANCE VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="Distance_km",
    y="Travel_Time_Minutes"
)

plt.title("Distance vs Travel Time")
plt.xlabel("Distance (km)")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# 28. SPEED VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="Avg_Speed_kmph",
    y="Travel_Time_Minutes"
)

plt.title("Average Speed vs Travel Time")
plt.xlabel("Average Speed (km/h)")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# 29. SIGNALS VS TRAVEL TIME

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="Number_of_Signals",
    y="Travel_Time_Minutes"
)

plt.title("Number of Signals vs Travel Time")
plt.xlabel("Number of Signals")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# EDA STARTS HERE
# ============================================================

print("\n")
print("=" * 50)
print("EXPLORATORY DATA ANALYSIS (EDA)")
print("=" * 50)


# ============================================================
# 30. HISTOGRAM - DISTANCE
# ============================================================

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="Distance_km",
    kde=True
)

plt.title("Distribution of Distance")
plt.xlabel("Distance (km)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()


# ============================================================
# 31. HISTOGRAM - AVERAGE SPEED
# ============================================================

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="Avg_Speed_kmph",
    kde=True
)

plt.title("Distribution of Average Speed")
plt.xlabel("Average Speed (km/h)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()


# ============================================================
# 32. HISTOGRAM - NUMBER OF SIGNALS
# ============================================================

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="Number_of_Signals",
    kde=True
)

plt.title("Distribution of Number of Signals")
plt.xlabel("Number of Signals")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()


# ============================================================
# 33. HISTOGRAM - TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x="Travel_Time_Minutes",
    kde=True
)

plt.title("Distribution of Travel Time")
plt.xlabel("Travel Time (Minutes)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()


# ============================================================
# 34. BOXPLOT - DISTANCE
# ============================================================

plt.figure(figsize=(8, 4))

sns.boxplot(
    data=df,
    x="Distance_km"
)

plt.title("Boxplot of Distance")
plt.xlabel("Distance (km)")
plt.tight_layout()
plt.show()


# ============================================================
# 35. BOXPLOT - AVERAGE SPEED
# ============================================================

plt.figure(figsize=(8, 4))

sns.boxplot(
    data=df,
    x="Avg_Speed_kmph"
)

plt.title("Boxplot of Average Speed")
plt.xlabel("Average Speed (km/h)")
plt.tight_layout()
plt.show()


# ============================================================
# 36. BOXPLOT - NUMBER OF SIGNALS
# ============================================================

plt.figure(figsize=(8, 4))

sns.boxplot(
    data=df,
    x="Number_of_Signals"
)

plt.title("Boxplot of Number of Signals")
plt.xlabel("Number of Signals")
plt.tight_layout()
plt.show()


# ============================================================
# 37. BOXPLOT - TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 4))

sns.boxplot(
    data=df,
    x="Travel_Time_Minutes"
)

plt.title("Boxplot of Travel Time")
plt.xlabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 38. CORRELATION HEATMAP
# ============================================================

plt.figure(figsize=(9, 6))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()


# ============================================================
# 39. DISTANCE VS TRAVEL TIME - EDA
# ============================================================

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="Distance_km",
    y="Travel_Time_Minutes"
)

plt.title("Distance vs Travel Time")
plt.xlabel("Distance (km)")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 40. SPEED VS TRAVEL TIME - EDA
# ============================================================

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="Avg_Speed_kmph",
    y="Travel_Time_Minutes"
)

plt.title("Average Speed vs Travel Time")
plt.xlabel("Average Speed (km/h)")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 41. SIGNALS VS TRAVEL TIME - EDA
# ============================================================

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x="Number_of_Signals",
    y="Travel_Time_Minutes"
)

plt.title("Number of Signals vs Travel Time")
plt.xlabel("Number of Signals")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 42. TRAFFIC LEVEL VS TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Traffic_Level",
    y="Travel_Time_Minutes"
)

plt.title("Traffic Level vs Travel Time")
plt.xlabel("Traffic Level")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 43. WEATHER VS TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Weather",
    y="Travel_Time_Minutes"
)

plt.title("Weather vs Travel Time")
plt.xlabel("Weather")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 44. ROAD TYPE VS TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Road_Type",
    y="Travel_Time_Minutes"
)

plt.title("Road Type vs Travel Time")
plt.xlabel("Road Type")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 45. VEHICLE TYPE VS TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Vehicle_Type",
    y="Travel_Time_Minutes"
)

plt.title("Vehicle Type vs Travel Time")
plt.xlabel("Vehicle Type")
plt.ylabel("Travel Time (Minutes)")
plt.tight_layout()
plt.show()


# ============================================================
# 46. TIME OF DAY VS TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Time_of_Day",
    y="Travel_Time_Minutes"
)

plt.title("Time of Day vs Travel Time")
plt.xlabel("Time of Day")
plt.ylabel("Travel Time (Minutes)")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()


# ============================================================
# 47. DAY OF WEEK VS TRAVEL TIME
# ============================================================

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Day_of_Week",
    y="Travel_Time_Minutes"
)

plt.title("Day of Week vs Travel Time")
plt.xlabel("Day of Week")
plt.ylabel("Travel Time (Minutes)")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()


# ============================================================
# 48. IQR OUTLIER ANALYSIS
# ============================================================

print("\n" + "=" * 50)
print("OUTLIER ANALYSIS USING IQR")
print("=" * 50)

for column in numerical_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ]

    print("\n" + column)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Number of Outliers:", len(outliers))


# ============================================================
# 49. EDA COMPLETED
# ============================================================

print("\n" + "=" * 50)
print("EDA COMPLETED SUCCESSFULLY")
print("=" * 50)