# -*- coding: utf-8 -*-
"""exp5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YQ2rBWPvgKsYp28YGUi0EHCuXDF4Wbx
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive/colab')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/colab/age_insurance.csv')

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ---------------------------------------------------------
# STEP 1: Load the data
# ---------------------------------------------------------
df = pd.read_csv("/content/drive/MyDrive/colab/age_insurance.csv")

print(df.head())
print(df.shape)


# ===========================================================
# PART 1: BINARY LOGISTIC REGRESSION
# Feature: Age -> Target: Insurance (0 = No, 1 = Yes)
# ===========================================================
print("\nPART 1: BINARY LOGISTIC REGRESSION")
print("-" * 45)

X = df[["Age"]]
y = df["Insurance"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

binary_model = LogisticRegression()
binary_model.fit(X_train, y_train)

y_pred = binary_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(
    classification_report(
        y_test,
        y_pred,
        target_names=["No Insurance", "Has Insurance"]
    )
)

print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))


# ---------------------------------------------------------
# Predict for new persons
# ---------------------------------------------------------
new_age = pd.DataFrame({"Age": [22, 45, 63]})

predictions = binary_model.predict(new_age)
print("Predictions:", predictions)

probabilities = binary_model.predict_proba(new_age)[:, 1]

for age_val, pred, prob in zip(
    new_age["Age"],
    predictions,
    probabilities
):
    print(
        f"Age {age_val}: Insurance = {pred} "
        f"(probability of Yes = {prob:.2f})"
    )


# ---------------------------------------------------------
# Plot: Age vs Insurance with S-curve
# ---------------------------------------------------------
plt.figure(figsize=(6, 4))

plt.scatter(
    df["Age"],
    df["Insurance"],
    color="blue",
    label="Actual data"
)

age_range = pd.DataFrame({
    "Age": range(18, 70)
})

plt.plot(
    age_range["Age"],
    binary_model.predict_proba(age_range)[:, 1],
    color="red",
    label="Predicted probability"
)

plt.xlabel("Age")
plt.ylabel("Insurance (0 = No, 1 = Yes)")
plt.title("Binary Logistic Regression: Age vs Insurance")

plt.legend()
plt.tight_layout()

plt.savefig("binary_logistic_plot.png")

plt.show()

print("\nSaved plot -> binary_logistic_plot.png")