# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AS6Ds-1FCC3_aUbN174SprdU-CuGL_fO
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab/placement_dataset.csv')

import os

print(os.listdir('/content/drive/MyDrive'))

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab/age_insurance.csv')

import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file == "age_insurance.csv":
            print(os.path.join(root, file))

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/colab/age_insurance.csv')

# Display first 5 rows
df.head()

# ---------------------------------------------------------
# Import Libraries
# ---------------------------------------------------------
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ---------------------------------------------------------
# STEP 1: Load the data
# ---------------------------------------------------------
df = pd.read_csv("/content/drive/MyDrive/colab/age_insurance.csv")

print("First 5 rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

# ---------------------------------------------------------
# STEP 2: Define Feature and Target
# ---------------------------------------------------------
X = df[["Age"]]
y = df["Insurance"]

# ---------------------------------------------------------
# STEP 3: Split the dataset
# ---------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ---------------------------------------------------------
# STEP 4: Train Logistic Regression Model
# ---------------------------------------------------------
binary_model = LogisticRegression()

binary_model.fit(X_train, y_train)

# ---------------------------------------------------------
# STEP 5: Predictions
# ---------------------------------------------------------
y_pred = binary_model.predict(X_test)

# ---------------------------------------------------------
# STEP 6: Evaluation
# ---------------------------------------------------------
print("\nAccuracy Score")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report")
print(classification_report(
    y_test,
    y_pred,
    target_names=["No Insurance", "Has Insurance"]
))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

# ---------------------------------------------------------
# STEP 7: Predict for New People
# ---------------------------------------------------------
new_age = pd.DataFrame({
    "Age": [22, 45, 63]
})

predictions = binary_model.predict(new_age)

probabilities = binary_model.predict_proba(new_age)[:, 1]

print("\nPredictions")

for age, pred, prob in zip(new_age["Age"], predictions, probabilities):
    print(f"Age = {age}")
    print(f"Insurance = {pred}")
    print(f"Probability of Insurance = {prob:.2f}")
    print()

# ---------------------------------------------------------
# STEP 8: Plot Logistic Regression Curve
# ---------------------------------------------------------
plt.figure(figsize=(7,5))

plt.scatter(
    df["Age"],
    df["Insurance"],
    color="blue",
    label="Actual Data"
)

age_range = pd.DataFrame({
    "Age": range(df["Age"].min(), df["Age"].max() + 1)
})

plt.plot(
    age_range["Age"],
    binary_model.predict_proba(age_range)[:, 1],
    color="red",
    linewidth=2,
    label="Logistic Curve"
)

plt.xlabel("Age")
plt.ylabel("Insurance (0 = No, 1 = Yes)")
plt.title("Binary Logistic Regression")
plt.legend()

plt.grid(True)

plt.tight_layout()

plt.savefig("binary_logistic_plot.png")

plt.show()

print("Plot saved as binary_logistic_plot.png")