# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RcBsT_yQaT9r_nH38T-u14e_amY8yPAj
"""

# -*- coding: utf-8 -*-

"""
AdaBoosting & XGBoost Benchmark
--------------------------------
Compares AdaBoost vs XGBoost on the placement dataset.
"""

# ==========================================================================
# 1. IMPORT LIBRARIES
# ==========================================================================

import time
import io
import numpy as np
import pandas as pd

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

from xgboost import XGBClassifier


# ==========================================================================
# 2. SETTINGS
# ==========================================================================

RANDOM_STATE = 42

# IMPORTANT:
# Your dataset contains "Placed", NOT "PlacementStatus"
TARGET_COL = "Placed"


# ==========================================================================
# 3. UPLOAD CSV FILE
# ==========================================================================

print("Please select your placement dataset CSV file.")

uploaded = files.upload()

DATA_PATH = next(iter(uploaded))

print("\nSelected file:", DATA_PATH)


# ==========================================================================
# 4. LOAD DATASET
# ==========================================================================

df = pd.read_csv(io.BytesIO(uploaded[DATA_PATH]))

print("\nDataset loaded successfully!")

print("\nDataset shape:")
print(df.shape)

print("\nFirst 5 rows:")
print(df.head())


# ==========================================================================
# 5. CHECK TARGET COLUMN
# ==========================================================================

if TARGET_COL not in df.columns:

    raise ValueError(
        f"Target column '{TARGET_COL}' was not found.\n"
        f"Available columns:\n{list(df.columns)}"
    )


# ==========================================================================
# 6. REMOVE IsAnomaly IF PRESENT
# ==========================================================================

if "IsAnomaly" in df.columns:

    df = df.drop(columns=["IsAnomaly"])

    print("\n'IsAnomaly' column removed.")


# ==========================================================================
# 7. SEPARATE TARGET AND FEATURES
# ==========================================================================

y = df[TARGET_COL].astype(int)

X = df.drop(columns=[TARGET_COL])


print("\nTarget column:")
print(TARGET_COL)

print("\nFeature columns:")
print(list(X.columns))


# ==========================================================================
# 8. REMOVE STUDENT ID
# ==========================================================================

# StudentID is only an identifier.
# It should not be used as a machine-learning feature.

if "StudentID" in X.columns:

    X = X.drop(columns=["StudentID"])

    print("\n'StudentID' removed because it is only an identifier.")


# ==========================================================================
# 9. IDENTIFY CATEGORICAL AND NUMERICAL COLUMNS
# ==========================================================================

cat_cols = X.select_dtypes(
    exclude="number"
).columns.tolist()

num_cols = X.select_dtypes(
    include="number"
).columns.tolist()


print("\nCategorical columns:")
print(cat_cols)

print("\nNumerical columns:")
print(num_cols)


# ==========================================================================
# 10. LABEL ENCODE CATEGORICAL COLUMNS
# ==========================================================================

encoders = {}

for c in cat_cols:

    le = LabelEncoder()

    X[c] = le.fit_transform(
        X[c].astype(str)
    )

    encoders[c] = le


print("\nCategorical columns encoded successfully.")


# ==========================================================================
# 11. HANDLE MISSING VALUES
# ==========================================================================

if len(num_cols) > 0:

    imputer = SimpleImputer(
        strategy="median"
    )

    X[num_cols] = imputer.fit_transform(
        X[num_cols]
    )


print("Missing values handled successfully.")


# ==========================================================================
# 12. SCALE NUMERICAL FEATURES
# ==========================================================================

if len(num_cols) > 0:

    scaler = StandardScaler()

    X[num_cols] = scaler.fit_transform(
        X[num_cols]
    )


print("Numerical features scaled successfully.")


# ==========================================================================
# 13. TRAIN / VALIDATION / TEST SPLIT
# ==========================================================================

VAL_SIZE = 0.15
TEST_SIZE = 0.15


# First create train+validation and test
X_train_val, X_test, y_train_val, y_test = train_test_split(

    X,
    y,

    test_size=TEST_SIZE,

    stratify=y,

    random_state=RANDOM_STATE
)


# Calculate validation ratio
val_ratio = VAL_SIZE / (1 - TEST_SIZE)


# Create train and validation sets
X_train, X_val, y_train, y_val = train_test_split(

    X_train_val,
    y_train_val,

    test_size=val_ratio,

    stratify=y_train_val,

    random_state=RANDOM_STATE
)


print("\n========================================")
print("DATA SPLIT")
print("========================================")

print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)


# ==========================================================================
# 14. BOOSTING BENCHMARK FUNCTION
# ==========================================================================

def boosting_benchmark(
    X_train,
    y_train,
    X_val,
    y_val
):

    results = []


    # ======================================================================
    # ADABOOST
    # ======================================================================

    print("\n========================================")
    print("TRAINING ADABOOST")
    print("========================================")


    # Weak learner
    ada_base = DecisionTreeClassifier(

        max_depth=2,

        random_state=RANDOM_STATE
    )


    # AdaBoost classifier
    ada = AdaBoostClassifier(

        estimator=ada_base,

        n_estimators=200,

        learning_rate=0.5,

        random_state=RANDOM_STATE
    )


    # Start timer
    t0 = time.time()


    # Train model
    ada.fit(
        X_train,
        y_train
    )


    # Training time
    ada_fit_time = time.time() - t0


    # Predictions
    ada_val_pred = ada.predict(
        X_val
    )


    # Probability predictions
    ada_val_proba = ada.predict_proba(
        X_val
    )[:, 1]


    # Metrics
    ada_accuracy = accuracy_score(
        y_val,
        ada_val_pred
    )

    ada_f1 = f1_score(
        y_val,
        ada_val_pred
    )

    ada_roc_auc = roc_auc_score(
        y_val,
        ada_val_proba
    )


    # Store results
    results.append({

        "model": "AdaBoost",

        "val_accuracy": ada_accuracy,

        "val_f1": ada_f1,

        "val_roc_auc": ada_roc_auc,

        "best_n_estimators": ada.n_estimators,

        "fit_time_sec": round(
            ada_fit_time,
            2
        )

    })


    print("AdaBoost training completed.")


    # ======================================================================
    # XGBOOST
    # ======================================================================

    print("\n========================================")
    print("TRAINING XGBOOST")
    print("========================================")


    xgb = XGBClassifier(

        n_estimators=1000,

        max_depth=4,

        learning_rate=0.05,

        subsample=0.8,

        colsample_bytree=0.8,

        eval_metric="logloss",

        early_stopping_rounds=30,

        random_state=RANDOM_STATE,

        n_jobs=-1
    )


    # Start timer
    t0 = time.time()


    # Train XGBoost
    xgb.fit(

        X_train,

        y_train,

        eval_set=[
            (X_val, y_val)
        ],

        verbose=False
    )


    # Training time
    xgb_fit_time = time.time() - t0


    # Predictions
    xgb_val_pred = xgb.predict(
        X_val
    )


    # Probability predictions
    xgb_val_proba = xgb.predict_proba(
        X_val
    )[:, 1]


    # Metrics
    xgb_accuracy = accuracy_score(
        y_val,
        xgb_val_pred
    )

    xgb_f1 = f1_score(
        y_val,
        xgb_val_pred
    )

    xgb_roc_auc = roc_auc_score(
        y_val,
        xgb_val_proba
    )


    # Best iteration
    best_iteration = xgb.best_iteration + 1


    # Store results
    results.append({

        "model": "XGBoost",

        "val_accuracy": xgb_accuracy,

        "val_f1": xgb_f1,

        "val_roc_auc": xgb_roc_auc,

        "best_n_estimators": best_iteration,

        "fit_time_sec": round(
            xgb_fit_time,
            2
        )

    })


    print("XGBoost training completed.")


    # ======================================================================
    # CREATE LEADERBOARD
    # ======================================================================

    results_df = pd.DataFrame(
        results
    )


    results_df = results_df.sort_values(

        "val_accuracy",

        ascending=False

    ).reset_index(drop=True)


    return results_df


# ==========================================================================
# 15. RUN BENCHMARK
# ==========================================================================

leaderboard = boosting_benchmark(

    X_train,

    y_train,

    X_val,

    y_val

)


# ==========================================================================
# 16. DISPLAY RESULTS
# ==========================================================================

print("\n\n========================================")
print("VALIDATION LEADERBOARD")
print("========================================")

print(
    leaderboard.to_string(
        index=False
    )
)


# ==========================================================================
# 17. SAVE RESULTS
# ==========================================================================

RESULT_FILE = "boosting_benchmark_results.csv"


leaderboard.to_csv(

    RESULT_FILE,

    index=False

)


print("\n========================================")
print("RESULT SAVED")
print("========================================")

print(
    f"Saved results to: {RESULT_FILE}"
)


# ==========================================================================
# 18. DOWNLOAD RESULTS
# ==========================================================================

files.download(
    RESULT_FILE
)