# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1lof80ebfeT_ffq_wPRRJ89gDDJPuzg
"""

# ============================================================
# DECISION TREE + RANDOM FOREST
# Placement Prediction
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


# ============================================================
# 1. CHOOSE / UPLOAD CSV FILE
# ============================================================

print("Please choose your placement CSV file:")

uploaded = files.upload()

# Automatically get the selected filename
file_name = next(iter(uploaded))

print("\nSelected file:", file_name)


# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv(file_name)

print("\nFirst 5 rows:")
print(df.head())

print("\nDataset shape:")
print(df.shape)


# ============================================================
# 3. REMOVE IsAnomaly IF PRESENT
# ============================================================

if "IsAnomaly" in df.columns:
    df = df.drop(columns=["IsAnomaly"])
    print("\nIsAnomaly column removed.")


# ============================================================
# 4. HANDLE MISSING VALUES
# ============================================================

for col in df.columns:

    if pd.api.types.is_numeric_dtype(df[col]):

        df[col] = df[col].fillna(
            df[col].median()
        )

    else:

        df[col] = df[col].fillna(
            df[col].mode()[0]
        )


print("\nMissing values handled.")


# ============================================================
# 5. DETERMINE TARGET COLUMN
# ============================================================

# Your dataset uses "Placed"
# Some versions may use "PlacementStatus"

if "Placed" in df.columns:

    TARGET = "Placed"

elif "PlacementStatus" in df.columns:

    TARGET = "PlacementStatus"

else:

    raise ValueError(
        "Target column not found. "
        "Expected 'Placed' or 'PlacementStatus'."
    )


print("\nTarget column:", TARGET)


# ============================================================
# 6. REMOVE STUDENT ID
# ============================================================

DROP_COLS = []

if "StudentID" in df.columns:

    DROP_COLS.append("StudentID")


# ============================================================
# 7. ENCODE CATEGORICAL COLUMNS IF PRESENT
# ============================================================

# Find categorical columns
categorical_columns = df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

# Do not encode the target
if TARGET in categorical_columns:
    categorical_columns.remove(TARGET)


if len(categorical_columns) > 0:

    print("\nCategorical columns found:")
    print(categorical_columns)

    df = pd.get_dummies(
        df,
        columns=categorical_columns,
        drop_first=True
    )

    print("Categorical columns encoded.")


# ============================================================
# 8. CREATE X AND Y
# ============================================================

X = df.drop(
    columns=[TARGET] + DROP_COLS,
    errors="ignore"
)

y = df[TARGET]


# Make target numeric if necessary
if not pd.api.types.is_numeric_dtype(y):

    y = pd.factorize(y)[0]


print("\nFeatures:")
print(list(X.columns))

print("\nNumber of features:", X.shape[1])


# ============================================================
# 9. TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y
)


print("\n========================================")
print("TRAIN / TEST SPLIT")
print("========================================")

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)


# ============================================================
# 10. DECISION TREE
# ============================================================

print("\n========================================")
print("DECISION TREE")
print("========================================")


dt = DecisionTreeClassifier(

    max_depth=4,

    random_state=42
)


dt.fit(
    X_train,
    y_train
)


# Prediction
y_pred_dt = dt.predict(
    X_test
)


# Accuracy
dt_accuracy = accuracy_score(
    y_test,
    y_pred_dt
)


print(
    f"Decision Tree Accuracy: {dt_accuracy:.4f}"
)


print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred_dt
    )
)


# ============================================================
# 11. DECISION TREE VISUALIZATION
# ============================================================

plt.figure(
    figsize=(20, 10)
)


plot_tree(

    dt,

    feature_names=X.columns,

    class_names=[
        "Not Placed",
        "Placed"
    ],

    filled=True,

    fontsize=8
)


plt.tight_layout()


plt.savefig(
    "decision_tree.png",
    dpi=150
)


plt.show()


print(
    "Decision Tree image saved as decision_tree.png"
)


# ============================================================
# 12. RANDOM FOREST
# ============================================================

print("\n========================================")
print("RANDOM FOREST")
print("========================================")


rf = RandomForestClassifier(

    n_estimators=100,

    max_features="sqrt",

    oob_score=True,

    random_state=42
)


rf.fit(
    X_train,
    y_train
)


# ============================================================
# 13. RANDOM FOREST PREDICTION
# ============================================================

y_pred_rf = rf.predict(
    X_test
)


rf_accuracy = accuracy_score(
    y_test,
    y_pred_rf
)


print(
    f"Random Forest Accuracy: {rf_accuracy:.4f}"
)


print(
    f"OOB Score: {rf.oob_score_:.4f}"
)


print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred_rf
    )
)


# ============================================================
# 14. RANDOM FOREST FEATURE IMPORTANCE
# ============================================================

print("\n========================================")
print("FEATURE IMPORTANCES")
print("========================================")


feature_importances = sorted(

    zip(
        X.columns,
        rf.feature_importances_
    ),

    key=lambda x: -x[1]
)


for name, importance in feature_importances:

    print(
        f"{name}: {importance:.4f}"
    )


# ============================================================
# 15. FINAL COMPARISON
# ============================================================

print("\n========================================")
print("MODEL COMPARISON")
print("========================================")

print(
    f"Decision Tree Accuracy : {dt_accuracy:.4f}"
)

print(
    f"Random Forest Accuracy : {rf_accuracy:.4f}"
)

print(
    f"Random Forest OOB Score: {rf.oob_score_:.4f}"
)


if rf_accuracy > dt_accuracy:

    print(
        "\nRandom Forest performed better."
    )

elif dt_accuracy > rf_accuracy:

    print(
        "\nDecision Tree performed better."
    )

else:

    print(
        "\nBoth models have the same accuracy."
    )


# ============================================================
# 16. DOWNLOAD DECISION TREE IMAGE
# ============================================================

files.download(
    "decision_tree.png"
)