# -*- coding: utf-8 -*-
"""Week-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CXKYxC1_WLnNCqUGqZDA2LC8meJ8UZC
"""

"""
PlacementPredict — Student Clustering: K-Means, Hierarchical, DBSCAN
=====================================================================

Goal: cluster students into behavioral/academic "profiles" WITHOUT using the
PlacementStatus label.

PlacementStatus is used only AFTER clustering to describe each cluster.
"""

# =====================================================================
# 0. GOOGLE COLAB - UPLOAD CSV
# =====================================================================

from google.colab import files
import io

print("Please upload your placement dataset CSV file...")

uploaded = files.upload()

# Get the uploaded filename automatically
filename = list(uploaded.keys())[0]

print(f"\nUploaded file: {filename}")


# =====================================================================
# 1. IMPORT LIBRARIES
# =====================================================================

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN

from sklearn.metrics import silhouette_score

from scipy.cluster.hierarchy import dendrogram, linkage


# =====================================================================
# SETTINGS
# =====================================================================

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)


NUMERIC_COLS = [
    "CGPA",
    "AttendancePercent",
    "Internships",
    "Projects",
    "Workshops",
    "Certifications",
    "Publications",
    "AptitudeTestScore",
    "SoftSkillsRating",
    "CodingTestScore",
    "MockInterviewScore",
]


CATEGORICAL_COLS = [
    "Gender",
    "City",
    "CollegeTier",
    "Stream",
    "Specialisation",
    "Hostel",
    "HistoryOfBacklogs",
    "ExtraCurricular",
]


print("=" * 70)
print("PLACEMENTPREDICT STUDENT CLUSTERING: K-Means / Hierarchical / DBSCAN")
print("=" * 70)


# =====================================================================
# 2. LOAD + PREPROCESS
# =====================================================================

# Read the uploaded CSV automatically
df = pd.read_csv(io.BytesIO(uploaded[filename]))

print(f"\nDataset loaded successfully!")
print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns)}")

print("\nDataset shape:", df.shape)


# ---------------------------------------------------------------------
# Handle missing numerical values
# ---------------------------------------------------------------------

imputer = SimpleImputer(strategy="median")

num_df = pd.DataFrame(
    imputer.fit_transform(df[NUMERIC_COLS]),
    columns=NUMERIC_COLS,
    index=df.index
)


# ---------------------------------------------------------------------
# Convert categorical columns into numbers
# ---------------------------------------------------------------------

cat_df = pd.get_dummies(
    df[CATEGORICAL_COLS],
    drop_first=True
)


# ---------------------------------------------------------------------
# Combine numerical + categorical features
# ---------------------------------------------------------------------

feature_df = pd.concat(
    [num_df, cat_df],
    axis=1
)


# ---------------------------------------------------------------------
# Standardize features
# ---------------------------------------------------------------------

X = StandardScaler().fit_transform(feature_df)


print(
    f"\nLoaded {len(df):,} students, "
    f"{feature_df.shape[1]} clustering features"
)

print("PlacementStatus & IsAnomaly excluded from clustering.")


# =====================================================================
# 3. CHOOSE K FOR K-MEANS
#    USING ELBOW + SILHOUETTE
# =====================================================================

k_range = range(2, 9)


# Take maximum 5000 samples for silhouette calculation
sample_size = min(5000, len(X))

sil_sample_idx = np.random.RandomState(
    RANDOM_STATE
).choice(
    len(X),
    sample_size,
    replace=False
)


X_sil_sample = X[sil_sample_idx]


inertias = []
sil_scores = []


for k in k_range:

    km_k = KMeans(
        n_clusters=k,
        n_init=10,
        random_state=RANDOM_STATE
    )

    labels_k = km_k.fit_predict(X)

    inertias.append(
        km_k.inertia_
    )

    sil_scores.append(
        silhouette_score(
            X_sil_sample,
            km_k.predict(X_sil_sample)
        )
    )


# ---------------------------------------------------------------------
# Plot Elbow + Silhouette
# ---------------------------------------------------------------------

fig, (ax1, ax2) = plt.subplots(
    1,
    2,
    figsize=(12, 4.5)
)


ax1.plot(
    list(k_range),
    inertias,
    marker="o"
)

ax1.set_title(
    "Elbow method (inertia)"
)

ax1.set_xlabel("k")

ax1.set_ylabel("Inertia")


ax2.plot(
    list(k_range),
    sil_scores,
    marker="o"
)

ax2.set_title(
    "Silhouette score vs k"
)

ax2.set_xlabel("k")

ax2.set_ylabel(
    "Silhouette score"
)


plt.tight_layout()

plt.savefig(
    "kmeans_elbow_silhouette.png",
    dpi=150
)

print(
    "\nSaved plot -> kmeans_elbow_silhouette.png"
)

plt.close(fig)


# ---------------------------------------------------------------------
# Select best K
# ---------------------------------------------------------------------

best_k = list(k_range)[
    int(np.argmax(sil_scores))
]


print(
    f"\nSilhouette-suggested k = {best_k}"
)


print(
    "Scores: "
    +
    ", ".join(
        f"k={k}:{s:.3f}"
        for k, s in zip(
            k_range,
            sil_scores
        )
    )
)


# =====================================================================
# 4. K-MEANS ON FULL DATASET
# =====================================================================

kmeans = KMeans(
    n_clusters=best_k,
    n_init=10,
    random_state=RANDOM_STATE
)


km_labels = kmeans.fit_predict(X)


sil = silhouette_score(
    X[sil_sample_idx],
    km_labels[sil_sample_idx]
)


print(
    f"\nK-Means (k={best_k}) "
    f"silhouette (sample): {sil:.3f}"
)


print(
    "Cluster sizes:",
    pd.Series(km_labels)
    .value_counts()
    .sort_index()
    .to_dict()
)


# =====================================================================
# 5. CLUSTER PROFILE
# =====================================================================

profiled = feature_df.copy()


profiled["KMeansCluster"] = km_labels


# PlacementStatus is used ONLY here
profiled["PlacementStatus"] = (
    df["PlacementStatus"].values
)


summary = profiled.groupby(
    "KMeansCluster"
).agg(

    n_students=(
        "PlacementStatus",
        "size"
    ),

    placement_rate=(
        "PlacementStatus",
        "mean"
    ),

    avg_CGPA=(
        "CGPA",
        "mean"
    ),

    avg_AttendancePercent=(
        "AttendancePercent",
        "mean"
    ),

    avg_AptitudeTestScore=(
        "AptitudeTestScore",
        "mean"
    ),

    avg_SoftSkillsRating=(
        "SoftSkillsRating",
        "mean"
    ),

    avg_CodingTestScore=(
        "CodingTestScore",
        "mean"
    ),

    avg_MockInterviewScore=(
        "MockInterviewScore",
        "mean"
    ),

    avg_Internships=(
        "Internships",
        "mean"
    ),

    avg_Projects=(
        "Projects",
        "mean"
    ),

).round(3)


print(
    "\n--- Cluster profiles (KMeansCluster) ---"
)

print(
    summary.to_string()
)


summary.to_csv(
    "cluster_profiles.csv"
)


print(
    "Saved table -> cluster_profiles.csv"
)


# =====================================================================
# 6. HIERARCHICAL CLUSTERING + DBSCAN
# =====================================================================

sub_idx = np.random.RandomState(
    RANDOM_STATE
).choice(
    len(X),
    min(5000, len(X)),
    replace=False
)


X_sub = X[sub_idx]


# ---------------------------------------------------------------------
# Hierarchical Clustering
# ---------------------------------------------------------------------

hc = AgglomerativeClustering(
    n_clusters=best_k,
    linkage="ward"
)


hc_labels = hc.fit_predict(X_sub)


sil_hc = silhouette_score(
    X_sub,
    hc_labels
)


print(
    f"\nHierarchical "
    f"(k={best_k}, subsample n={len(X_sub)}) "
    f"silhouette: {sil_hc:.3f}"
)


# ---------------------------------------------------------------------
# DBSCAN
# ---------------------------------------------------------------------

db = DBSCAN(
    eps=4.0,
    min_samples=15
)


db_labels = db.fit_predict(X_sub)


n_db_clusters = (
    len(set(db_labels))
    -
    (1 if -1 in db_labels else 0)
)


n_noise = int(
    np.sum(db_labels == -1)
)


print(
    f"DBSCAN "
    f"(subsample n={len(X_sub)}): "
    f"{n_db_clusters} clusters, "
    f"{n_noise} noise points"
)


if n_db_clusters >= 2:

    mask = db_labels != -1

    print(
        "DBSCAN silhouette "
        f"(excluding noise): "
        f"{silhouette_score(X_sub[mask], db_labels[mask]):.3f}"
    )


# =====================================================================
# 7. DENDROGRAM
# =====================================================================

dendro_idx = np.random.choice(
    len(X_sub),
    size=min(80, len(X_sub)),
    replace=False
)


Z = linkage(
    X_sub[dendro_idx],
    method="ward"
)


plt.figure(
    figsize=(12, 5)
)


dendrogram(Z)


plt.title(
    "Hierarchical Clustering Dendrogram"
)


plt.xlabel(
    "Student index"
)


plt.ylabel(
    "Distance"
)


plt.tight_layout()


plt.savefig(
    "dendrogram.png",
    dpi=150
)


print(
    "Saved plot -> dendrogram.png"
)


plt.close()


# =====================================================================
# 8. PCA FOR VISUALIZATION
# =====================================================================

X_pca_full = PCA(
    n_components=2,
    random_state=RANDOM_STATE
).fit_transform(X)


# ---------------------------------------------------------------------
# K-Means PCA plot
# ---------------------------------------------------------------------

fig, ax = plt.subplots(
    figsize=(6, 5.2)
)


ax.scatter(
    X_pca_full[:, 0],
    X_pca_full[:, 1],
    c=km_labels,
    cmap="tab10",
    s=8,
    alpha=0.6
)


ax.set_title(
    f"K-Means, full data ({best_k} clusters)"
)


ax.set_xlabel("PC1")


ax.set_ylabel("PC2")


plt.tight_layout()


plt.savefig(
    "kmeans_pca.png",
    dpi=150
)


print(
    "Saved plot -> kmeans_pca.png"
)


plt.close(fig)


# =====================================================================
# 9. HIERARCHICAL + DBSCAN PCA PLOT
# =====================================================================

fig, axes = plt.subplots(
    1,
    2,
    figsize=(12, 5.2)
)


coords_sub = X_pca_full[sub_idx]


# Hierarchical
axes[0].scatter(
    coords_sub[:, 0],
    coords_sub[:, 1],
    c=hc_labels,
    cmap="tab10",
    s=8,
    alpha=0.6
)


axes[0].set_title(
    f"Hierarchical, subsample ({best_k} clusters)"
)


# DBSCAN
noise_mask = db_labels == -1


axes[1].scatter(
    coords_sub[~noise_mask, 0],
    coords_sub[~noise_mask, 1],
    c=db_labels[~noise_mask],
    cmap="tab10",
    s=8,
    alpha=0.6
)


axes[1].scatter(
    coords_sub[noise_mask, 0],
    coords_sub[noise_mask, 1],
    c="lightgray",
    s=8,
    alpha=0.5,
    marker="x",
    label="noise"
)


axes[1].legend(
    loc="upper right",
    fontsize=8
)


axes[1].set_title(
    f"DBSCAN, subsample ({n_db_clusters} clusters)"
)


for ax in axes:

    ax.set_xlabel("PC1")

    ax.set_ylabel("PC2")


plt.tight_layout()


plt.savefig(
    "hierarchical_dbscan_pca.png",
    dpi=150
)


print(
    "Saved plot -> hierarchical_dbscan_pca.png"
)


plt.close(fig)


# =====================================================================
# 10. SAVE FINAL DATASET
# =====================================================================

df_out = df.copy()


df_out["KMeansCluster"] = km_labels


df_out.to_csv(
    "placement_predict_with_clusters.csv",
    index=False
)


print(
    "\nSaved deliverable -> "
    "placement_predict_with_clusters.csv"
)


# =====================================================================
# DONE
# =====================================================================

print(
    "\nDone!"
)

print(
    "K-Means gives a scalable segmentation of students "
    "into different profiles."
)

print(
    "Placement rate is calculated AFTER clustering "
    "to understand each profile."
)